openapi: 3.0.3
info:
  title: Price
  description: 'Generate price'
  version: 1.0.0
tags:
  - name: Price
    description: Price
paths:
  /prices:
    get:
      tags:
        - Price
      summary: Returns information prices
      operationId: getPrice
      parameters:
        - in: query
          name: productId
          allowEmptyValue: false
          description: Product identifier.
          required: true
          schema:
            type: integer
        - in: query
          name: brandId
          allowEmptyValue: false
          description: Group identifier.
          required: true
          schema:
            type: integer
        - in: query
          name: applyDate
          allowEmptyValue: false
          description: application date (yyyy-MM-dd-HH.mm.ss)
          required: true
          schema:
            type: string
      responses:
        200:
          description: Price to apply
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'

        400:
          description: Malformed syntax of the request params
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/PriceError'
              example:
                status: 400
                title: Bad Request
                detail: Wrong value in the application Date parameter

        500:
          description: Server encountered an unexpected problem
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/PriceError'
              example:
                status: 500
                title: Internal server error
                detail: Unexpected server error
components:
  schemas:
    PriceResponse:
      description: Product object returned by the API
      type: object
      properties:
        productId:
          description: Product identifier
          type: integer
        brandId:
          description: Brand identifier
          type: integer
        priceList:
          description: Price application
          type: integer
        startDate:
          description: application date
          type: string
          format: date-time
          example: yyyy-MM-dd-HH.mm.ss
        endDate:
          description: application date
          type: string
          format: date-time
          example: yyyy-MM-dd-HH.mm.ss
        price:
          description: Final apply price
          type: number
          format: double
    PriceError:
      type: object
      properties:
        title:
          type: string
          description: A short, summary of the problem type
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
        detail:
          type: string
          description: Detail of Problem
